image: node:6
pages:
  cache:
    paths:
    - $HOME/.yarn-cache
  stage: deploy
  script:
  - npm install -g yarn
  - yarn
  - npm run clean
  - NODE_ENV=production npm run build
  artifacts:
    paths:
    - public
