image: node:6
pages:
  cache:
    paths:
    - node_modules/
  script:
  - npm install
  - npm run clean
  - NODE_ENV=production npm run build
  artifacts:
    paths:
    - public
  only:
    - master
